### PR TITLE
fix: the error message should always display the correct number of arguments it received

### PR DESCRIPTION
**Pull request by SuperFola**
# Fixing error messages

## Description

Changing the way we count received arguments in arity / type errors for failed function call. The stack now returns a `Value(ValueType::Undefined)` when it's empty (as a failsafe) instead of Nil. The typechecker takes this in account to generate error messages accordingly.

## Checklist

- [x] I have read the [Contributor guide](CONTRIBUTING.md)
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation if needed
- [ ] I have added tests that prove my fix/feature is working
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by rakista112** [comment]
Might be good. undefined is more descriptive than Nil, Arkscript doesn't have exceptions
It would be good if those are the only situations we can get ::Undefined, else it would lead to confusion.

**Comment by SuperFola** [comment]
Nil and undefined will coexist, one is meant to be exposed (nil), the other is a purely internal value to mark non existing values (undefined), it should (and will) never leak to the end user. My use of the value is purely internal to the VM so that we can mark when values aren't "real" (the stack being an array default init every values on it, thus we needed a way to mark values as "not really there").

**Comment by rakista112** [comment]
Ah, yeah that sounds convenient for internals. Could it also be used for C++ modules?

**Comment by SuperFola** [comment]
There is no use for Undefined in modules, since they interact directly with the end user ; if the module creator wants to return a "nothing" value it should be Nil since it'll end up in the end user code.

I guess your idea was to return Undefined to have like a "no return", but the VM won't like it since everything must return a value, and Undefined isn't one.

**Pull request merged**
