### PR TITLE
Optimize Dockerfile

### PR DESCRIPTION
**Pull request by yardenshoham**
By separating the stages of the build, I was able to reduce the image's size from 508MB to 456MB.

### CODE REVIEW

**Comment by SuperFola** [comment]
I'm currently looking into it as well, I think after building everything we can remove unecessary components, such as make for example

**Comment by yardenshoham** [comment]
Alright, the major thing I was able to remove was the `.git` directory. Try to use what I did and seperate the `builder` stage.

**Comment by SuperFola** [comment]
That's clever!

Also after build we can just get rid of lib/ext, since the modules (when compiled) are moved to lib/[name].arkm by cmake.

Haven't tried yet but adding after having finished `RUN apk del cmake clang clang-dev make gcc g++` should do the work

**Comment by yardenshoham** [comment]
Well, in Docker you can't actually delete stuff, only add... unless you introduce a new stage. I can suggest a `runner` stage that copies the necessary files from the `builder` stage and installs `Ark`. But I don't know which files to take after the build is done.

**Comment by SuperFola** [comment]
I see

Well the only needed files to make it work would be Ark itself, and then the whole lib/ folder (without lib/ext/)

**Comment by SuperFola** [comment]
Will merge for now to see how far we can get step after step (don't mind the failed checks, that's just the labeler being silly)

**Pull request merged**
